In [180]:
import pandas as pd
import csv
import matplotlib as mp
import numpy as np
import os
from IPython.display import display, HTML
import graphlab as gl
from graphlab import SFrame

In [181]:
india_folder = 'data/All_States/'

In [251]:
 df = pd.read_csv(india_folder + "chandigarh.csv")
df = df.replace('-', value=0)

In [252]:
df = df.transpose()
display(df)

,0,1,2,3,4,5,6,7,8,9,...,44,45,46,47,48,49,50,51,52,53
indicators,Total Teachers (Elementary),% Teachers: Government,% Teachers: Private Aided,% Teachers: Private Unaided,Pupil-Teacher Ratio: Elementary,% Female Teachers,% SC Teachers,% ST Teachers,% OBC Teachers,% Teachers Recieved in-Service Training,...,Total Schools,Total Government Schools,Total Private Schools,Ratio of Primary to U.PrimarySch2./6S.1ec.,Primary Sch./Sec.per 1000 Child Popln.,U.Prim. Sch./Sec.per 1000 Child Popln.,% Single-Teacher Schools with Enr.≥15,% Enrolment in Single-Teacher Schools,% Schools with Enrolment 2≤0 5.00,% Schools with Female Te1a8c.h9ers
2005-06,4862,0,0,0,24,83.1,0,0,0,14.5,...,185,0,0,1.2,2,2,0,0,4.9,98.9
2007-08,5519,60.5,2.7,36.8,24,81.3,7.9,0.2,4.2,15,...,176,110,66,1.1,2,2,0,0,1.7,100
2008-09,5762,61.5,2.6,36,25,80.9,8.2,0.3,5.2,23.9,...,177,112,65,1.1,2,2,0,0,1.1,99.4
2009-10,4922,60.3,2.2,37.5,29,83.3,8.3,0.2,5.2,15.6,...,176,112,64,1.1,2,3,0,0,1.1,99.4
2010-11,6179,45.5,6.2,33.9,24,82.6,6.3,0.2,4,0.7,...,184,114,68,1.1,2,3,0,0,3.8,97.3
2011-12,5462,50.9,3.3,42.1,29,81.8,8,0.2,5.6,16.6,...,187,111,76,1.1,2,3,0,0,2.1,100
2012-13,7524,55,3.2,41.8,21,82.8,7.3,0.2,5.5,15.2,...,188,110,78,1.1,2,3,0,0,1.1,100
2013-14,8555,56.7,3,40.3,19,80.9,7.7,0.6,7.1,13.8,...,192,112,80,1,2,3,0,0,1,100
2014-15,8553,55.8,2.9,40.8,19,81,8,0.5,7.4,6.1,...,197,113,80,1,2,3,0,0,1,100
2015-16,9309,58.4,3.1,37.7,17,78.9,8.7,0.6,9,8.7,...,201,115,80,1,2,3,0,0,0.5,100

In [253]:
df.columns = df.iloc[0]
df = df[1:]
display(df)

indicators,Total Teachers (Elementary),% Teachers: Government,% Teachers: Private Aided,% Teachers: Private Unaided,Pupil-Teacher Ratio: Elementary,% Female Teachers,% SC Teachers,% ST Teachers,% OBC Teachers,% Teachers Recieved in-Service Training,...,Total Schools,Total Government Schools,Total Private Schools,Ratio of Primary to U.PrimarySch2./6S.1ec.,Primary Sch./Sec.per 1000 Child Popln.,U.Prim. Sch./Sec.per 1000 Child Popln.,% Single-Teacher Schools with Enr.≥15,% Enrolment in Single-Teacher Schools,% Schools with Enrolment 2≤0 5.00,% Schools with Female Te1a8c.h9ers
2005-06,4862,0,0,0,24,83.1,0,0,0,14.5,...,185,0,0,1.2,2,2,0,0,4.9,98.9
2007-08,5519,60.5,2.7,36.8,24,81.3,7.9,0.2,4.2,15,...,176,110,66,1.1,2,2,0,0,1.7,100
2008-09,5762,61.5,2.6,36,25,80.9,8.2,0.3,5.2,23.9,...,177,112,65,1.1,2,2,0,0,1.1,99.4
2009-10,4922,60.3,2.2,37.5,29,83.3,8.3,0.2,5.2,15.6,...,176,112,64,1.1,2,3,0,0,1.1,99.4
2010-11,6179,45.5,6.2,33.9,24,82.6,6.3,0.2,4,0.7,...,184,114,68,1.1,2,3,0,0,3.8,97.3
2011-12,5462,50.9,3.3,42.1,29,81.8,8,0.2,5.6,16.6,...,187,111,76,1.1,2,3,0,0,2.1,100
2012-13,7524,55,3.2,41.8,21,82.8,7.3,0.2,5.5,15.2,...,188,110,78,1.1,2,3,0,0,1.1,100
2013-14,8555,56.7,3,40.3,19,80.9,7.7,0.6,7.1,13.8,...,192,112,80,1,2,3,0,0,1,100
2014-15,8553,55.8,2.9,40.8,19,81,8,0.5,7.4,6.1,...,197,113,80,1,2,3,0,0,1,100
2015-16,9309,58.4,3.1,37.7,17,78.9,8.7,0.6,9,8.7,...,201,115,80,1,2,3,0,0,0.5,100

In [254]:
print df.dtypes
for colname, col in df.iteritems():
    l = col.tolist()
    print "before list"
    print l
    l = [float(i) for i in l]
    df[colname] = l
    print df[colname].dtype

indicators
Total Teachers (Elementary)                   object
% Teachers: Government                        object
% Teachers: Private Aided                     object
% Teachers: Private Unaided                   object
Pupil-Teacher Ratio: Elementary               object
% Female Teachers                             object
% SC Teachers                                 object
% ST Teachers                                 object
% OBC Teachers                                object
% Teachers Recieved in-Service Training       object
% Contract Teachers to Total Teachers         object
Enrolment: Classes I-V                        object
Enrolment: Classes VI-VIII                    object
Enrolment: Classes I-V, Government            object
Enrolment:Classes VI-VIII,Gove99rn.9ment      object
Enrolment: Classes I-V, Privat1e00.0          object
Enrolment: Classes VI-VIII, Private           object
% Girls Enrolment: Primary Le9v8e.l8          object
% Girls Enrolment: U.Primary L9e9.v6el        object
Ratio of Girls Enr.to Boys: Primary           object
Ratio of Girls Enr.to Boys: U.Primary         object
% SC Enrolment: Classes I-VIII                object
% ST Enrolment: Classes  I-VII9I 9.4          object
% OBC Enrolment: Primary Level                object
% OBC Enrolment:U.Primary Level               object
% Muslim Enrolment: Primary 9L8e.v8el         object
% Muslim Enrolment: U. Prima9r7y. 4Level      object
Ratio of Grade V to I                         object
Avg. Repetition Rate: Primary Level           object
Avg.Repetition Rate: U.Primary Level          object
Avg. Drop-out Rate: Primary Le9v9e.1l         object
Retention Rate: Primary Level                 object
Transition Rate: Primary to U.Primary         object
Student-Classroom Ratio                       object
% Schools with Drinking Water                 object
% Schools with Common Toilet                  object
% Schools with Boys' Toilet                   object
% Schools with Girls' Toilet                  object
% Schools with Boundarywall                   object
% School with Playground Facility             object
% Schools with Ramp                           object
% Schools havining Electricity                object
% Schools with Computer                       object
Number of Districts Cove16re.6d               object
Total Schools                                 object
Total Government Schools                      object
Total Private Schools                         object
Ratio of Primary to U.PrimarySch2./6S.1ec.    object
Primary Sch./Sec.per 1000 Child Popln.        object
U.Prim. Sch./Sec.per 1000 Child Popln.        object
% Single-Teacher Schools with Enr.≥15         object
% Enrolment in Single-Teacher Schools         object
% Schools with Enrolment 2≤0 5.00             object
% Schools with Female Te1a8c.h9ers            object
dtype: object
before list
['4862', '5519', '5762', '4922', '6179', '5462', '7524', '8555', '8553', '9309']
float64
before list
[0, '60.5', '61.5', '60.3', '45.5', '50.9', '55', '56.7', '55.8', '58.4']
float64
before list
[0, '2.7', '2.6', '2.2', '6.2', '3.3', '3.2', '3', '2.9', '3.1']
float64
before list
[0, '36.8', '36', '37.5', '33.9', '42.1', '41.8', '40.3', '40.8', '37.7']
float64
before list
['24', '24', '25', '29', '24', '29', '21', '19', '19', '17']
float64
before list
['83.1', '81.3', '80.9', '83.3', '82.6', '81.8', '82.8', '80.9', '81', '78.9']
float64
before list
[0, '7.9', '8.2', '8.3', '6.3', '8', '7.3', '7.7', '8', '8.7']
float64
before list
[0, '0.2', '0.3', '0.2', '0.2', '0.2', '0.2', '0.6', '0.5', '0.6']
float64
before list
[0, '4.2', '5.2', '5.2', '4', '5.6', '5.5', '7.1', '7.4', '9']
float64
before list
['14.5', '15', '23.9', '15.6', '0.7', '16.6', '15.2', '13.8', '6.1', '8.7']
float64
before list
['1.3', '1.5', '16.9', '20.8', '18.3', '17.8', 0, 0, '28.2', '25.4']
float64
before list
['76279', '86250', '89729', '89871', '93786', '98214', '96729', '97524', '96367', '93230']
float64
before list
['42777', '48461', '51473', '52474', '55216', '58655', '62163', '63661', '64376', '64691']
float64
before list
[0, '60845', '63475', '62823', '65702', '64038', '64643', '64122', '61972', '57920']
float64
before list
[0, '32951', '35550', '36421', '38742', '38500', '43189', '44090', '44519', '43964']
float64
before list
[0, '25405', '26254', '27048', '28069', '31038', '32086', '33402', '34001', '34507']
float64
before list
[0, '15510', '15923', '16053', '16474', '18003', '18974', '19571', '19734', '20533']
float64
before list
['45.5', '44.7', '45', '45.5', '45.9', '46.5', '46.8', '46.8', '46.6', '46.7']
float64
before list
['46.4', '44.6', '44.8', '44.4', '44.1', '43.9', '44.2', '44.2', '45.2', '45.7']
float64
before list
['0.83', '0.81', '0.82', '0.84', '0.85', '0.87', '0.88', '0.88', '0.87', '0.88']
float64
before list
['0.86', '0.81', '0.81', '0.8', '0.79', '0.78', '0.79', '0.79', '0.82', '0.84']
float64
before list
['12.9', '10.6', '9.3', '10.1', '10.3', '10.4', '8.9', '10.2', '9.9', '9.5']
float64
before list
['0.1', '0.1', '0.1', '0.2', '0.1', '0.1', '0', '0.2', '0.2', '0.2']
float64
before list
['1.7', '1.3', '1', '1.2', '1.3', '1.4', '1.1', '1.5', '1.6', '1.7']
float64
before list
['0.9', '1', '0.8', '1.5', '1.7', '1.7', '1.3', '2', '2.3', '2.3']
float64
before list
[0, '3.8', '4.7', '5.3', '5.2', '5.1', '3.2', '5.2', '5.5', '5.7']
float64
before list
[0, '2.8', '3.7', '4.1', '4.6', '4.6', '2.6', '5.2', '5.5', '5.7']
float64
before list
['96', '94', 0, 0, 0, 0, 0, 0, 0, 0]
float64
before list
['2.9', '2.4', '2.8', '2.1', '1.4', '0.3', '0.1', '0.1', '0.2', '0.2']
float64
before list
[0, '3.4', '9.3', '7.8', '3.2', '0.3', '0.1', '0.1', '0.2', '0.1']
float64
before list
[0, '29.5', 0, 0, 0, '8', '9', 0, 0, 0]
float64
before list
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
float64
before list
[0, '97.4', 0, '97.5', 0, 0, 0, 0, 0, 0]
float64
before list
['27', '28', '30', '40', '43', '41', '43', '42', '40', '39']
float64
before list
['99.5', '100', '100', '100', '100', '100', '100', '100', '100', '100']
float64
before list
['36.2', '38.1', '40.1', '32.4', 0, 0, 0, 0, 0, 0]
float64
before list
[0, 0, 0, '93.2', '92.9', '100', '100', '100', '100', '100']
float64
before list
['89.2', '94.9', '94.9', '97.2', '95.1', '100', '100', '100', '100', '100']
float64
before list
['97.3', '100', '99.4', '99.4', '100', '100', '98.9', '99.5', '100', '100']
float64
before list
[0, 0, 0, '98.3', '95.1', '92.17', '95.2', '93.8', '92.9', '93']
float64
before list
['28.7', '35.2', '39', '43.2', '43.5', '46.5', '97.6', '95.2', '87.6', '88.7']
float64
before list
[0, 0, '100', '100', '100', '100', '100', '100', '100', '100']
float64
before list
['71.4', '76.1', '85.9', '90.3', '93.5', '94.7', '96.3', '95.8', '95.4', '94.5']
float64
before list
['1', '1', '1', '1', '1', '1', '1', '1', '1', '1']
float64
before list
['185', '176', '177', '176', '184', '187', '188', '192', '197', '201']
float64
before list
[0, '110', '112', '112', '114', '111', '110', '112', '113', '115']
float64
before list
[0, '66', '65', '64', '68', '76', '78', '80', '80', '80']
float64
before list
['1.2', '1.1', '1.1', '1.1', '1.1', '1.1', '1.1', '1', '1', '1']
float64
before list
['2', '2', '2', '2', '2', '2', '2', '2', '2', '2']
float64
before list
['2', '2', '2', '3', '3', '3', '3', '3', '3', '3']
float64
before list
['0', '0', '0', '0', '0', '0', '0', '0', '0', '0']
float64
before list
['0', '0', '0', '0', '0', '0', '0', '0', '0', '0']
float64
before list
['4.9', '1.7', '1.1', '1.1', '3.8', '2.1', '1.1', '1', '1', '0.5']
float64
before list
['98.9', '100', '99.4', '99.4', '97.3', '100', '100', '100', '100', '100']
float64

In [255]:
df.dtypes

indicators
Total Teachers (Elementary)                   float64
% Teachers: Government                        float64
% Teachers: Private Aided                     float64
% Teachers: Private Unaided                   float64
Pupil-Teacher Ratio: Elementary               float64
% Female Teachers                             float64
% SC Teachers                                 float64
% ST Teachers                                 float64
% OBC Teachers                                float64
% Teachers Recieved in-Service Training       float64
% Contract Teachers to Total Teachers         float64
Enrolment: Classes I-V                        float64
Enrolment: Classes VI-VIII                    float64
Enrolment: Classes I-V, Government            float64
Enrolment:Classes VI-VIII,Gove99rn.9ment      float64
Enrolment: Classes I-V, Privat1e00.0          float64
Enrolment: Classes VI-VIII, Private           float64
% Girls Enrolment: Primary Le9v8e.l8          float64
% Girls Enrolment: U.Primary L9e9.v6el        float64
Ratio of Girls Enr.to Boys: Primary           float64
Ratio of Girls Enr.to Boys: U.Primary         float64
% SC Enrolment: Classes I-VIII                float64
% ST Enrolment: Classes  I-VII9I 9.4          float64
% OBC Enrolment: Primary Level                float64
% OBC Enrolment:U.Primary Level               float64
% Muslim Enrolment: Primary 9L8e.v8el         float64
% Muslim Enrolment: U. Prima9r7y. 4Level      float64
Ratio of Grade V to I                         float64
Avg. Repetition Rate: Primary Level           float64
Avg.Repetition Rate: U.Primary Level          float64
Avg. Drop-out Rate: Primary Le9v9e.1l         float64
Retention Rate: Primary Level                 float64
Transition Rate: Primary to U.Primary         float64
Student-Classroom Ratio                       float64
% Schools with Drinking Water                 float64
% Schools with Common Toilet                  float64
% Schools with Boys' Toilet                   float64
% Schools with Girls' Toilet                  float64
% Schools with Boundarywall                   float64
% School with Playground Facility             float64
% Schools with Ramp                           float64
% Schools havining Electricity                float64
% Schools with Computer                       float64
Number of Districts Cove16re.6d               float64
Total Schools                                 float64
Total Government Schools                      float64
Total Private Schools                         float64
Ratio of Primary to U.PrimarySch2./6S.1ec.    float64
Primary Sch./Sec.per 1000 Child Popln.        float64
U.Prim. Sch./Sec.per 1000 Child Popln.        float64
% Single-Teacher Schools with Enr.≥15         float64
% Enrolment in Single-Teacher Schools         float64
% Schools with Enrolment 2≤0 5.00             float64
% Schools with Female Te1a8c.h9ers            float64
dtype: object

In [257]:
display(df)
df.columns.values

indicators,Total Teachers (Elementary),% Teachers: Government,% Teachers: Private Aided,% Teachers: Private Unaided,Pupil-Teacher Ratio: Elementary,% Female Teachers,% SC Teachers,% ST Teachers,% OBC Teachers,% Teachers Recieved in-Service Training,...,Total Schools,Total Government Schools,Total Private Schools,Ratio of Primary to U.PrimarySch2./6S.1ec.,Primary Sch./Sec.per 1000 Child Popln.,U.Prim. Sch./Sec.per 1000 Child Popln.,% Single-Teacher Schools with Enr.≥15,% Enrolment in Single-Teacher Schools,% Schools with Enrolment 2≤0 5.00,% Schools with Female Te1a8c.h9ers
2005-06,4862.0,0.0,0.0,0.0,24.0,83.1,0.0,0.0,0.0,14.5,...,185.0,0.0,0.0,1.2,2.0,2.0,0.0,0.0,4.9,98.9
2007-08,5519.0,60.5,2.7,36.8,24.0,81.3,7.9,0.2,4.2,15.0,...,176.0,110.0,66.0,1.1,2.0,2.0,0.0,0.0,1.7,100.0
2008-09,5762.0,61.5,2.6,36.0,25.0,80.9,8.2,0.3,5.2,23.9,...,177.0,112.0,65.0,1.1,2.0,2.0,0.0,0.0,1.1,99.4
2009-10,4922.0,60.3,2.2,37.5,29.0,83.3,8.3,0.2,5.2,15.6,...,176.0,112.0,64.0,1.1,2.0,3.0,0.0,0.0,1.1,99.4
2010-11,6179.0,45.5,6.2,33.9,24.0,82.6,6.3,0.2,4.0,0.7,...,184.0,114.0,68.0,1.1,2.0,3.0,0.0,0.0,3.8,97.3
2011-12,5462.0,50.9,3.3,42.1,29.0,81.8,8.0,0.2,5.6,16.6,...,187.0,111.0,76.0,1.1,2.0,3.0,0.0,0.0,2.1,100.0
2012-13,7524.0,55.0,3.2,41.8,21.0,82.8,7.3,0.2,5.5,15.2,...,188.0,110.0,78.0,1.1,2.0,3.0,0.0,0.0,1.1,100.0
2013-14,8555.0,56.7,3.0,40.3,19.0,80.9,7.7,0.6,7.1,13.8,...,192.0,112.0,80.0,1.0,2.0,3.0,0.0,0.0,1.0,100.0
2014-15,8553.0,55.8,2.9,40.8,19.0,81.0,8.0,0.5,7.4,6.1,...,197.0,113.0,80.0,1.0,2.0,3.0,0.0,0.0,1.0,100.0
2015-16,9309.0,58.4,3.1,37.7,17.0,78.9,8.7,0.6,9.0,8.7,...,201.0,115.0,80.0,1.0,2.0,3.0,0.0,0.0,0.5,100.0

array(['Total Teachers (Elementary)', '% Teachers: Government',
       '% Teachers: Private Aided', '% Teachers: Private Unaided',
       'Pupil-Teacher Ratio: Elementary', '% Female Teachers',
       '% SC Teachers', '% ST Teachers', '% OBC Teachers',
       '% Teachers Recieved in-Service Training',
       '% Contract Teachers to Total Teachers', 'Enrolment: Classes I-V',
       'Enrolment: Classes VI-VIII', 'Enrolment: Classes I-V, Government',
       'Enrolment:Classes VI-VIII,Gove99rn.9ment',
       'Enrolment: Classes I-V, Privat1e00.0',
       'Enrolment: Classes VI-VIII, Private',
       '% Girls Enrolment: Primary Le9v8e.l8',
       '% Girls Enrolment: U.Primary L9e9.v6el',
       'Ratio of Girls Enr.to Boys: Primary',
       'Ratio of Girls Enr.to Boys: U.Primary',
       '% SC Enrolment: Classes I-VIII',
       '% ST Enrolment: Classes  I-VII9I 9.4',
       '% OBC Enrolment: Primary Level', '% OBC Enrolment:U.Primary Level',
       '% Muslim Enrolment: Primary 9L8e.v8el',
       '% Muslim Enrolment: U. Prima9r7y. 4Level', 'Ratio of Grade V to I',
       'Avg. Repetition Rate: Primary Level',
       'Avg.Repetition Rate: U.Primary Level',
       'Avg. Drop-out Rate: Primary Le9v9e.1l',
       'Retention Rate: Primary Level',
       'Transition Rate: Primary to U.Primary', 'Student-Classroom Ratio',
       '% Schools with Drinking Water', '% Schools with Common Toilet',
       "% Schools with Boys' Toilet", "% Schools with Girls' Toilet",
       '% Schools with Boundarywall', '% School with Playground Facility',
       '% Schools with Ramp', '% Schools havining Electricity',
       '% Schools with Computer', 'Number of Districts Cove16re.6d',
       'Total Schools', 'Total Government Schools',
       'Total Private Schools',
       'Ratio of Primary to U.PrimarySch2./6S.1ec.',
       'Primary Sch./Sec.per 1000 Child Popln.',
       'U.Prim. Sch./Sec.per 1000 Child Popln.',
       '% Single-Teacher Schools with Enr.\xe2\x89\xa515',
       '% Enrolment in Single-Teacher Schools',
       '% Schools with Enrolment 2\xe2\x89\xa40 5.00',
       '% Schools with Female Te1a8c.h9ers'], dtype=object)

In [258]:
df.replace(0.0,np.nan)

indicators,Total Teachers (Elementary),% Teachers: Government,% Teachers: Private Aided,% Teachers: Private Unaided,Pupil-Teacher Ratio: Elementary,% Female Teachers,% SC Teachers,% ST Teachers,% OBC Teachers,% Teachers Recieved in-Service Training,...,Total Schools,Total Government Schools,Total Private Schools,Ratio of Primary to U.PrimarySch2./6S.1ec.,Primary Sch./Sec.per 1000 Child Popln.,U.Prim. Sch./Sec.per 1000 Child Popln.,% Single-Teacher Schools with Enr.≥15,% Enrolment in Single-Teacher Schools,% Schools with Enrolment 2≤0 5.00,% Schools with Female Te1a8c.h9ers
2005-06,4862.0,NaN,NaN,NaN,24.0,83.1,NaN,NaN,NaN,14.5,...,185.0,NaN,NaN,1.2,2.0,2.0,NaN,NaN,4.9,98.9
2007-08,5519.0,60.5,2.7,36.8,24.0,81.3,7.9,0.2,4.2,15.0,...,176.0,110.0,66.0,1.1,2.0,2.0,NaN,NaN,1.7,100.0
2008-09,5762.0,61.5,2.6,36.0,25.0,80.9,8.2,0.3,5.2,23.9,...,177.0,112.0,65.0,1.1,2.0,2.0,NaN,NaN,1.1,99.4
2009-10,4922.0,60.3,2.2,37.5,29.0,83.3,8.3,0.2,5.2,15.6,...,176.0,112.0,64.0,1.1,2.0,3.0,NaN,NaN,1.1,99.4
2010-11,6179.0,45.5,6.2,33.9,24.0,82.6,6.3,0.2,4.0,0.7,...,184.0,114.0,68.0,1.1,2.0,3.0,NaN,NaN,3.8,97.3
2011-12,5462.0,50.9,3.3,42.1,29.0,81.8,8.0,0.2,5.6,16.6,...,187.0,111.0,76.0,1.1,2.0,3.0,NaN,NaN,2.1,100.0
2012-13,7524.0,55.0,3.2,41.8,21.0,82.8,7.3,0.2,5.5,15.2,...,188.0,110.0,78.0,1.1,2.0,3.0,NaN,NaN,1.1,100.0
2013-14,8555.0,56.7,3.0,40.3,19.0,80.9,7.7,0.6,7.1,13.8,...,192.0,112.0,80.0,1.0,2.0,3.0,NaN,NaN,1.0,100.0
2014-15,8553.0,55.8,2.9,40.8,19.0,81.0,8.0,0.5,7.4,6.1,...,197.0,113.0,80.0,1.0,2.0,3.0,NaN,NaN,1.0,100.0
2015-16,9309.0,58.4,3.1,37.7,17.0,78.9,8.7,0.6,9.0,8.7,...,201.0,115.0,80.0,1.0,2.0,3.0,NaN,NaN,0.5,100.0

In [259]:
sf = SFrame(data=df)

In [260]:
model = gl.linear_regression.create(sf, target="Transition Rate: Primary to U.Primary", features=['Total Teachers (Elementary)', '% Teachers: Government',
       '% Teachers: Private Aided', '% Teachers: Private Unaided',
       'Pupil-Teacher Ratio: Elementary', '% Female Teachers',
       '% SC Teachers', '% ST Teachers', '% OBC Teachers',
       '% Teachers Recieved in-Service Training',
       '% Contract Teachers to Total Teachers', 'Enrolment: Classes I-V',
       'Enrolment: Classes VI-VIII', 'Enrolment: Classes I-V, Government',
       'Enrolment:Classes VI-VIII,Gove99rn.9ment',
       'Enrolment: Classes I-V, Privat1e00.0',
       'Enrolment: Classes VI-VIII, Private',
       '% Girls Enrolment: Primary Le9v8e.l8',
       '% Girls Enrolment: U.Primary L9e9.v6el',
       'Ratio of Girls Enr.to Boys: Primary',
       'Ratio of Girls Enr.to Boys: U.Primary',
       '% SC Enrolment: Classes I-VIII',
       '% ST Enrolment: Classes  I-VII9I 9.4',
       '% OBC Enrolment: Primary Level', '% OBC Enrolment:U.Primary Level',
       '% Muslim Enrolment: Primary 9L8e.v8el',
       '% Muslim Enrolment: U. Prima9r7y. 4Level', 'Ratio of Grade V to I',
       'Avg. Repetition Rate: Primary Level',
       'Avg.Repetition Rate: U.Primary Level',
       'Avg. Drop-out Rate: Primary Le9v9e.1l',
       'Retention Rate: Primary Level',
        'Student-Classroom Ratio',
       '% Schools with Drinking Water', '% Schools with Common Toilet',
       "% Schools with Boys' Toilet", "% Schools with Girls' Toilet",
       '% Schools with Boundarywall', '% School with Playground Facility',
       '% Schools with Ramp', '% Schools havining Electricity',
       '% Schools with Computer', 'Number of Districts Cove16re.6d',
       'Total Schools', 'Total Government Schools',
       'Total Private Schools',
       'Ratio of Primary to U.PrimarySch2./6S.1ec.',
       'Primary Sch./Sec.per 1000 Child Popln.',
       'U.Prim. Sch./Sec.per 1000 Child Popln.',
       '% Single-Teacher Schools with Enr.\xe2\x89\xa515',
       '% Enrolment in Single-Teacher Schools',
       '% Schools with Enrolment 2\xe2\x89\xa40 5.00',
       '% Schools with Female Te1a8c.h9ers'])

WARNING: The number of feature dimensions in this problem is very large in comparison with the number of examples. Unless an appropriate regularization value is set, this model may not provide accurate predictions for a validation/test set.

WARNING: Detected extremely low variance for feature(s) 'Retention Rate: Primary Level', 'Number of Districts Cove16re.6d', 'Primary Sch./Sec.per 1000 Child Popln.', '% Single-Teacher Schools with Enr.≥15', '% Enrolment in Single-Teacher Schools' because all entries are nearly the same.
Proceeding with model training using all features. If the model does not provide results of adequate quality, exclude the above mentioned feature(s) from the input dataset.

Linear regression:

--------------------------------------------------------

Number of examples          : 10

Number of features          : 53

Number of unpacked features : 53

Number of coefficients    : 54

Starting Newton Method

--------------------------------------------------------

+-----------+----------+--------------+--------------------+---------------+

| Iteration | Passes   | Elapsed Time | Training-max_error | Training-rmse |

+-----------+----------+--------------+--------------------+---------------+

| 1         | 2        | 0.001023     | 0.553544           | 0.287382      |

+-----------+----------+--------------+--------------------+---------------+

SUCCESS: Optimal solution found.

In [261]:
print model.coefficients

+-------------------------------+-------+--------------------+--------+
|              name             | index |       value        | stderr |
+-------------------------------+-------+--------------------+--------+
|          (intercept)          |  None |   -76.8182365258   |  None  |
|  Total Teachers (Elementary)  |  None | -0.000672653111976 |  None  |
|     % Teachers: Government    |  None |   0.131607767669   |  None  |
|   % Teachers: Private Aided   |  None |   -2.02328422798   |  None  |
|  % Teachers: Private Unaided  |  None |  -0.063443888248   |  None  |
| Pupil-Teacher Ratio: Eleme... |  None |   0.155277280815   |  None  |
|       % Female Teachers       |  None |  0.00845574689115  |  None  |
|         % SC Teachers         |  None |   0.776077356753   |  None  |
|         % ST Teachers         |  None |   -34.3163904682   |  None  |
|         % OBC Teachers        |  None |   0.688647420014   |  None  |
+-------------------------------+-------+--------------------+--------+
[54 rows x 4 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [262]:
print type(model.coefficients)

<class 'graphlab.data_structures.sframe.SFrame'>

In [263]:
result = model.coefficients.to_dataframe()

In [264]:
display(result)

                                          name index         value stderr
0                                  (intercept)  None -7.681824e+01   None
1                  Total Teachers (Elementary)  None -6.726531e-04   None
2                       % Teachers: Government  None  1.316078e-01   None
3                    % Teachers: Private Aided  None -2.023284e+00   None
4                  % Teachers: Private Unaided  None -6.344389e-02   None
5              Pupil-Teacher Ratio: Elementary  None  1.552773e-01   None
6                            % Female Teachers  None  8.455747e-03   None
7                                % SC Teachers  None  7.760774e-01   None
8                                % ST Teachers  None -3.431639e+01   None
9                               % OBC Teachers  None  6.886474e-01   None
10     % Teachers Recieved in-Service Training  None -1.014772e+00   None
11       % Contract Teachers to Total Teachers  None -4.529494e-01   None
12                      Enrolment: Classes I-V  None -3.944933e-05   None
13                  Enrolment: Classes VI-VIII  None -5.202194e-05   None
14          Enrolment: Classes I-V, Government  None -2.143475e-05   None
15    Enrolment:Classes VI-VIII,Gove99rn.9ment  None -2.121845e-05   None
16        Enrolment: Classes I-V, Privat1e00.0  None -4.800779e-05   None
17         Enrolment: Classes VI-VIII, Private  None -6.236686e-06   None
18        % Girls Enrolment: Primary Le9v8e.l8  None -5.629963e-03   None
19      % Girls Enrolment: U.Primary L9e9.v6el  None  3.638657e-03   None
20         Ratio of Girls Enr.to Boys: Primary  None  7.120867e-02   None
21       Ratio of Girls Enr.to Boys: U.Primary  None  9.862244e-01   None
22              % SC Enrolment: Classes I-VIII  None -5.980258e-03   None
23        % ST Enrolment: Classes  I-VII9I 9.4  None  1.564677e+02   None
24              % OBC Enrolment: Primary Level  None  9.012334e-01   None
25             % OBC Enrolment:U.Primary Level  None  3.280826e+00   None
26       % Muslim Enrolment: Primary 9L8e.v8el  None  4.013503e-01   None
27    % Muslim Enrolment: U. Prima9r7y. 4Level  None -1.346395e+00   None
28                       Ratio of Grade V to I  None  4.490018e-01   None
29         Avg. Repetition Rate: Primary Level  None  7.041506e+00   None
30        Avg.Repetition Rate: U.Primary Level  None  5.334120e+00   None
31       Avg. Drop-out Rate: Primary Le9v9e.1l  None  2.160832e+00   None
32               Retention Rate: Primary Level  None  0.000000e+00   None
33                     Student-Classroom Ratio  None  1.655079e-01   None
34               % Schools with Drinking Water  None  1.028269e-04   None
35                % Schools with Common Toilet  None  1.012381e+00   None
36                 % Schools with Boys' Toilet  None  3.730722e-01   None
37                % Schools with Girls' Toilet  None  6.324636e-04   None
38                 % Schools with Boundarywall  None -1.081739e-03   None
39           % School with Playground Facility  None  4.810803e-01   None
40                         % Schools with Ramp  None -7.198654e-03   None
41              % Schools havining Electricity  None -1.153485e-01   None
42                     % Schools with Computer  None -1.158694e-02   None
43             Number of Districts Cove16re.6d  None -2.485701e-11   None
44                               Total Schools  None -7.955245e-03   None
45                    Total Government Schools  None  2.430566e-02   None
46                       Total Private Schools  None -4.634375e-02   None
47  Ratio of Primary to U.PrimarySch2./6S.1ec.  None  8.835109e-01   None
48      Primary Sch./Sec.per 1000 Child Popln.  None -1.239137e-11   None
49      U.Prim. Sch./Sec.per 1000 Child Popln.  None  3.954790e+00   None
50       % Single-Teacher Schools with Enr.≥15  None  0.000000e+00   None
51       % Enrolment in Single-Teacher Schools  None  0.000000e+00   None
52           % Schools with Enrolment 2≤0 5.00  None -7.272648e+00   None
53          % Schools with Female Te1a8c.h9ers  None -8.898098e-04   None

In [265]:
result.to_csv(india_folder +"reg_coefficient/chandigarh_result.csv", index=False)