In [570]:
import pandas as pd
import csv
import matplotlib as mp
import numpy as np
import os
from IPython.display import display, HTML
import graphlab as gl
from graphlab import SFrame

In [571]:
india_folder = 'data/All_States/'

In [656]:
 df = pd.read_csv(india_folder + "west_bengal.csv")
df = df.replace('-', value=0)
df = df.replace(' -', value=0)
df = df.replace('- ', value=0)

In [657]:
df = df.transpose()
display(df)

,0,1,2,3,4,5,6,7,8,9,...,43,44,45,46,47,48,49,50,51,52
indicators,Total Teachers (Elementary),% Teachers: Government,% Teachers: Private Aided,% Teachers: Private Unaided,Pupil-Teacher Ratio: Elementary,% Female Teachers,% SC Teachers,% ST Teachers,% OBC Teachers,% Teachers Recieved in-Service Training,...,Total Schools,Total Government Schools,Total Private Schools,Ratio of Primary to U.P5r.i0marySch./Sec.,Primary Sch./Sec.per 1000 Child Popln.,U.Prim. Sch./Sec.per 1000 Child Popln.,% Single-Teacher Schools with Enr.≥15,% Enrolment in Single-Teacher Schools,% Schools with Enro4l.m3 ent ≤ 50,% Schools with Fem4a.1le Teachers
2005-06,234278,0,0,0,54,27.7,0,0,0,33.1,...,59223,0,0,5.3,6,2,4.9,2.1,8.8,52.8
2007-08,274052,92.9,4.9,2.2,48,32.4,19.5,4.5,6.7,51.6,...,70010,57461,12523,5.6,7,2,3.1,1.2,15.3,68.5
2008-09,272923,91.8,5.4,2.8,47,33.6,19.6,4.6,7,50.6,...,70771,57344,13427,5.5,2,8,4,1.5,18.4,70.4
2009-10,381018,82.3,1.4,16.4,39,43.1,18.1,4.1,7.1,42.1,...,88556,77181,11362,5.5,10,3,5.5,2.3,15.8,73
2010-11,494297,83.9,0.8,11.2,30,41.2,18.8,4.4,7.5,28.9,...,90187,79119,8708,5.1,10,3,2.6,1,18.5,74.1
2011-12,529703,84.6,0.6,10.7,28,41,19.3,4.5,7.9,32.7,...,92066,81363,8273,4.7,10,3,2.7,1,19.8,75
2012-13,537047,82.8,0.7,12.4,27,41.6,19.3,4.6,8.4,36.3,...,94572,82259,9445,4.5,10,3,3.3,1.1,23,74.8
2013-14,536830,81.6,0.7,13.1,25,42,19.4,4.8,8.9,23.1,...,94958,81915,9657,4.4,10,4,3.2,1.3,30.4,75
2014-15,566484,81.3,0.6,13.5,23,42.2,19.6,4.7,10,16.6,...,95572,82444,9725,4.3,10,4,2.6,1,32.6,75
2015-16,565646,80.3,0.4,14.7,23,42.6,19.6,4.6,10.5,10.1,...,95723,82737,9754,4.2,10,4,3,1.1,33.3,75

In [658]:
df.columns = df.iloc[0]
df = df[1:]
display(df)

indicators,Total Teachers (Elementary),% Teachers: Government,% Teachers: Private Aided,% Teachers: Private Unaided,Pupil-Teacher Ratio: Elementary,% Female Teachers,% SC Teachers,% ST Teachers,% OBC Teachers,% Teachers Recieved in-Service Training,...,Total Schools,Total Government Schools,Total Private Schools,Ratio of Primary to U.P5r.i0marySch./Sec.,Primary Sch./Sec.per 1000 Child Popln.,U.Prim. Sch./Sec.per 1000 Child Popln.,% Single-Teacher Schools with Enr.≥15,% Enrolment in Single-Teacher Schools,% Schools with Enro4l.m3 ent ≤ 50,% Schools with Fem4a.1le Teachers
2005-06,234278,0,0,0,54,27.7,0,0,0,33.1,...,59223,0,0,5.3,6,2,4.9,2.1,8.8,52.8
2007-08,274052,92.9,4.9,2.2,48,32.4,19.5,4.5,6.7,51.6,...,70010,57461,12523,5.6,7,2,3.1,1.2,15.3,68.5
2008-09,272923,91.8,5.4,2.8,47,33.6,19.6,4.6,7,50.6,...,70771,57344,13427,5.5,2,8,4,1.5,18.4,70.4
2009-10,381018,82.3,1.4,16.4,39,43.1,18.1,4.1,7.1,42.1,...,88556,77181,11362,5.5,10,3,5.5,2.3,15.8,73
2010-11,494297,83.9,0.8,11.2,30,41.2,18.8,4.4,7.5,28.9,...,90187,79119,8708,5.1,10,3,2.6,1,18.5,74.1
2011-12,529703,84.6,0.6,10.7,28,41,19.3,4.5,7.9,32.7,...,92066,81363,8273,4.7,10,3,2.7,1,19.8,75
2012-13,537047,82.8,0.7,12.4,27,41.6,19.3,4.6,8.4,36.3,...,94572,82259,9445,4.5,10,3,3.3,1.1,23,74.8
2013-14,536830,81.6,0.7,13.1,25,42,19.4,4.8,8.9,23.1,...,94958,81915,9657,4.4,10,4,3.2,1.3,30.4,75
2014-15,566484,81.3,0.6,13.5,23,42.2,19.6,4.7,10,16.6,...,95572,82444,9725,4.3,10,4,2.6,1,32.6,75
2015-16,565646,80.3,0.4,14.7,23,42.6,19.6,4.6,10.5,10.1,...,95723,82737,9754,4.2,10,4,3,1.1,33.3,75

In [659]:
print df.dtypes
for colname, col in df.iteritems():
    l = col.tolist()
    print "before list"
    print l
    l = [float(i) for i in l]
    df[colname] = l
    print df[colname].dtype

indicators
Total Teachers (Elementary)                  object
% Teachers: Government                       object
% Teachers: Private Aided                    object
% Teachers: Private Unaided                  object
Pupil-Teacher Ratio: Elementary              object
% Female Teachers                            object
% SC Teachers                                object
% ST Teachers                                object
% OBC Teachers                               object
% Teachers Recieved in-Service Training      object
Enrolment: Classes I-V                       object
Enrolment: Classes VI-VIII                   object
Enrolment: Classes I-V, Government           object
Enrolment:Classes VI-VIII,7G8.o5vernment     object
Enrolment: C1la8s.8ses I-V, Private          object
Enrolment: Classes VI-VIII, Private          object
% Girls Enrolment: P5r3im.2ary Level         object
% Girls Enrol1m9e.1nt: U.Primary Level       object
Ratio of Girls Enr.to Boys: Primary          object
Ratio of Girls Enr.to Boys: U.Primary        object
% SC Enrolment: Classes I-VIII               object
% ST Enrolment: Cla5s2s.e5s  I-VIII          object
% OBC Enrolment: Primary Level               object
% OBC Enrolment:U.Primary Level              object
% Muslim Enrolment5: 1P.6rimary Level        object
% Muslim En1ro9.lm5 ent: U. Primary Level    object
Ratio of Grade V to I                        object
Avg. Repetition Rate: Primary Level          object
Avg.Repetition Rate: U.Primary Level         object
Avg. Drop-out Rate: 5P0r.i9mary Level        object
Retention Rate: Primary Level                object
Transition Rate: Primary to U.Primary        object
Student-Classroom Ratio                      object
% Schools with Drinking Water                object
% Schools with Common Toilet                 object
% Schools with Boys' Toilet                  object
% Schools with Girls' Toilet                 object
% Schools with Boundarywall                  object
% School with Playground Facility            object
% Schools with Ramp                          object
% Schools havining Electricity               object
% Schools with Computer                      object
Number of Districts 4C.0overed               object
Total Schools                                object
Total Government Schools                     object
Total Private Schools                        object
Ratio of Primary to U.P5r.i0marySch./Sec.    object
Primary Sch./Sec.per 1000 Child Popln.       object
U.Prim. Sch./Sec.per 1000 Child Popln.       object
% Single-Teacher Schools with Enr.≥15        object
% Enrolment in Single-Teacher Schools        object
% Schools with Enro4l.m3 ent ≤ 50            object
% Schools with Fem4a.1le Teachers            object
dtype: object
before list
['234278', '274052', '272923', 381018.0, '494297', '529703', '537047', '536830', '566484', '565646']
float64
before list
[0, '92.9', '91.8', 82.3, '83.9', '84.6', '82.8', '81.6', '81.3', '80.3']
float64
before list
[0, '4.9', '5.4', 1.4, '0.8', '0.6', '0.7', '0.7', '0.6', '0.4']
float64
before list
[0, '2.2', '2.8', 16.4, '11.2', '10.7', '12.4', '13.1', '13.5', '14.7']
float64
before list
['54', '48', '47', 39.0, '30', '28', '27', '25', '23', '23']
float64
before list
['27.7', '32.4', '33.6', 43.1, '41.2', '41', '41.6', '42', '42.2', '42.6']
float64
before list
[0, '19.5', '19.6', 18.1, '18.8', '19.3', '19.3', '19.4', '19.6', '19.6']
float64
before list
[0, '4.5', '4.6', 4.1, '4.4', '4.5', '4.6', '4.8', '4.7', '4.6']
float64
before list
[0, '6.7', '7', 7.1, '7.5', '7.9', '8.4', '8.9', '10', '10.5']
float64
before list
['33.1', '51.6', '50.6', 42.1, '28.9', '32.7', '36.3', '23.1', '16.6', '10.1']
float64
before list
['9005975', '9463730', '9013013', 10545319.0, '10231570', '10086047', '9731912', '8437717', '8163021', '8131797']
float64
before list
['3586358', '3807261', '3944515', 4495475.0, '4700195', '4741910', '4748869', '4842905', '4852086', '4777237']
float64
before list
[0, '8314874', '7996328', 9295090.0, '9120325', '8875151', '8573022', '7333775', '7056511', '6858090']
float64
before list
[0, '3228091', '3328645', 4083078.0, '4317590', '4350663', '4399322', '4477080', '4468815', '4335795']
float64
before list
[0, '1148856', '1016685', 1250229.0, '869119', '910278', '871604', '829700', '826590', '965528']
float64
before list
[0, '579170', '615870', 412397.0, '155451', '155191', '125119', '133359', '136712', '177908']
float64
before list
['49.6', '49.1', '49.2', 49.4, '49.4', '49.5', '49.4', '49.2', '49', '49']
float64
before list
['49', '49.6', '50.3', 51.4, '51.6', '51.9', '52', '52', '51.8', '51.6']
float64
before list
['0.98', '0.96', '0.97', 0.98, '0.98', '0.98', '0.98', '0.97', '0.96', '0.96']
float64
before list
['0.96', '0.98', '1.01', 1.06, '1.07', '1.08', '1.08', '1.08', '1.07', '1.07']
float64
before list
['27.7', '26.8', '27.4', 26.6, '26.6', '27.2', '27.1', '27.6', '27.6', '26.9']
float64
before list
['6.2', '6.3', '6.3', 6.8, '6.9', '7.1', '7.1', '7.2', '7.2', '7.1']
float64
before list
['4.5', '4.5', '4.7', 4.3, '4.6', '4.9', '7.5', '10.1', '10.8', '11.6']
float64
before list
['8.4', '8.8', '8.8', 8.7, '9.2', '9.5', '11.5', '14.3', '15.5', '16.5']
float64
before list
[0, '28.1', '28.3', 32.3, '31.7', '32.2', '32.3', '33.2', '34.5', '35.1']
float64
before list
[0, '18.9', '20.1', 26.5, '26.7', '28.8', '28', '29.6', '30.8', '31.4']
float64
before list
['80', '74', '79', 69.0, '73', '75', '77', 0, '98', '97']
float64
before list
['13.6', '13.1', '12', 9.0, '11.2', '10.9', '9.2', '4.6', '1.9', '1.3']
float64
before list
[0, '19.8', '15.5', 7.9, '8.7', '7.4', '5.6', '2', '0.8', '0.6']
float64
before list
['11.6', '9.4', '8', 8.7, '6.5', '6.6', '6.6', '6.3', '2.9', '1.5']
float64
before list
[0, '51.9', '58.2', 73.5, '68.5', '81.4', '75', '60.8', '62.7', '65.2']
float64
before list
[0, '79.5', '69.9', 85.9, '82.4', '83.7', '84.2', '92.4', '96', '97.7']
float64
before list
['55', '51', '47', 42.0, '40', '41', '37', '32', '30', '29']
float64
before list
['83', '78.8', '82.7', 96.0, '95.4', '97.2', '97.4', '97.8', '97.9', '98.4']
float64
before list
['65.4', '69', '74.3', 80.0, 0, 0, 0, 0, 0, 0]
float64
before list
[0, 0, 0, 16.0, '32.7', '85.4', '39.9', '94', '96.5', '97.7']
float64
before list
['30.6', '35.1', '41.2', 48.9, '48.8', '54.7', '74.9', '71.7', '86.9', '98.3']
float64
before list
['32.9', '41.4', '40.1', 0.0, '32.7', '35.6', '36.1', '39.7', '43.1', '43.5']
float64
before list
[0, 0, 0, 36.8, '34.3', '32.3', '33.1', '34.5', '38.4', '40.4']
float64
before list
['8.9', '53.4', '57.3', 49.6, '49.2', '47.7', '87.6', '89.3', '90.2', '91.9']
float64
before list
[0, 0, '24.9', 26.5, '28.8', '31.7', '35.5', '41', '57', '74.9']
float64
before list
['4.5', '5', '5.9', 7.5, '8.7', '8.8', '9.7', '10.8', '12.1', '12.7']
float64
before list
['20', '20', '20', 20.0, '20', '20', '20', '20', '21', '21']
float64
before list
['59223', '70010', '70771', 88556.0, '90187', '92066', '94572', '94958', '95572', '95723']
float64
before list
[0, '57461', '57344', 77181.0, '79119', '81363', '82259', '81915', '82444', '82737']
float64
before list
[0, '12523', '13427', 11362.0, '8708', '8273', '9445', '9657', '9725', '9754']
float64
before list
['5.3', '5.6', '5.5', 5.5, '5.1', '4.7', '4.5', '4.4', '4.3', '4.2']
float64
before list
['6', '7', '2', 10.0, '10', '10', '10', '10', '10', '10']
float64
before list
['2', '2', '8', 3.0, '3', '3', '3', '4', '4', '4']
float64
before list
['4.9', '3.1', '4', 5.5, '2.6', '2.7', '3.3', '3.2', '2.6', '3']
float64
before list
['2.1', '1.2', '1.5', 2.3, '1', '1', '1.1', '1.3', '1', '1.1']
float64
before list
['8.8', '15.3', '18.4', 15.8, '18.5', '19.8', '23', '30.4', '32.6', '33.3']
float64
before list
['52.8', '68.5', '70.4', 73.0, '74.1', '75', '74.8', '75', '75', '75']
float64

In [660]:
df.dtypes

indicators
Total Teachers (Elementary)                  float64
% Teachers: Government                       float64
% Teachers: Private Aided                    float64
% Teachers: Private Unaided                  float64
Pupil-Teacher Ratio: Elementary              float64
% Female Teachers                            float64
% SC Teachers                                float64
% ST Teachers                                float64
% OBC Teachers                               float64
% Teachers Recieved in-Service Training      float64
Enrolment: Classes I-V                       float64
Enrolment: Classes VI-VIII                   float64
Enrolment: Classes I-V, Government           float64
Enrolment:Classes VI-VIII,7G8.o5vernment     float64
Enrolment: C1la8s.8ses I-V, Private          float64
Enrolment: Classes VI-VIII, Private          float64
% Girls Enrolment: P5r3im.2ary Level         float64
% Girls Enrol1m9e.1nt: U.Primary Level       float64
Ratio of Girls Enr.to Boys: Primary          float64
Ratio of Girls Enr.to Boys: U.Primary        float64
% SC Enrolment: Classes I-VIII               float64
% ST Enrolment: Cla5s2s.e5s  I-VIII          float64
% OBC Enrolment: Primary Level               float64
% OBC Enrolment:U.Primary Level              float64
% Muslim Enrolment5: 1P.6rimary Level        float64
% Muslim En1ro9.lm5 ent: U. Primary Level    float64
Ratio of Grade V to I                        float64
Avg. Repetition Rate: Primary Level          float64
Avg.Repetition Rate: U.Primary Level         float64
Avg. Drop-out Rate: 5P0r.i9mary Level        float64
Retention Rate: Primary Level                float64
Transition Rate: Primary to U.Primary        float64
Student-Classroom Ratio                      float64
% Schools with Drinking Water                float64
% Schools with Common Toilet                 float64
% Schools with Boys' Toilet                  float64
% Schools with Girls' Toilet                 float64
% Schools with Boundarywall                  float64
% School with Playground Facility            float64
% Schools with Ramp                          float64
% Schools havining Electricity               float64
% Schools with Computer                      float64
Number of Districts 4C.0overed               float64
Total Schools                                float64
Total Government Schools                     float64
Total Private Schools                        float64
Ratio of Primary to U.P5r.i0marySch./Sec.    float64
Primary Sch./Sec.per 1000 Child Popln.       float64
U.Prim. Sch./Sec.per 1000 Child Popln.       float64
% Single-Teacher Schools with Enr.≥15        float64
% Enrolment in Single-Teacher Schools        float64
% Schools with Enro4l.m3 ent ≤ 50            float64
% Schools with Fem4a.1le Teachers            float64
dtype: object

In [661]:
display(df)
df.columns.values

indicators,Total Teachers (Elementary),% Teachers: Government,% Teachers: Private Aided,% Teachers: Private Unaided,Pupil-Teacher Ratio: Elementary,% Female Teachers,% SC Teachers,% ST Teachers,% OBC Teachers,% Teachers Recieved in-Service Training,...,Total Schools,Total Government Schools,Total Private Schools,Ratio of Primary to U.P5r.i0marySch./Sec.,Primary Sch./Sec.per 1000 Child Popln.,U.Prim. Sch./Sec.per 1000 Child Popln.,% Single-Teacher Schools with Enr.≥15,% Enrolment in Single-Teacher Schools,% Schools with Enro4l.m3 ent ≤ 50,% Schools with Fem4a.1le Teachers
2005-06,234278.0,0.0,0.0,0.0,54.0,27.7,0.0,0.0,0.0,33.1,...,59223.0,0.0,0.0,5.3,6.0,2.0,4.9,2.1,8.8,52.8
2007-08,274052.0,92.9,4.9,2.2,48.0,32.4,19.5,4.5,6.7,51.6,...,70010.0,57461.0,12523.0,5.6,7.0,2.0,3.1,1.2,15.3,68.5
2008-09,272923.0,91.8,5.4,2.8,47.0,33.6,19.6,4.6,7.0,50.6,...,70771.0,57344.0,13427.0,5.5,2.0,8.0,4.0,1.5,18.4,70.4
2009-10,381018.0,82.3,1.4,16.4,39.0,43.1,18.1,4.1,7.1,42.1,...,88556.0,77181.0,11362.0,5.5,10.0,3.0,5.5,2.3,15.8,73.0
2010-11,494297.0,83.9,0.8,11.2,30.0,41.2,18.8,4.4,7.5,28.9,...,90187.0,79119.0,8708.0,5.1,10.0,3.0,2.6,1.0,18.5,74.1
2011-12,529703.0,84.6,0.6,10.7,28.0,41.0,19.3,4.5,7.9,32.7,...,92066.0,81363.0,8273.0,4.7,10.0,3.0,2.7,1.0,19.8,75.0
2012-13,537047.0,82.8,0.7,12.4,27.0,41.6,19.3,4.6,8.4,36.3,...,94572.0,82259.0,9445.0,4.5,10.0,3.0,3.3,1.1,23.0,74.8
2013-14,536830.0,81.6,0.7,13.1,25.0,42.0,19.4,4.8,8.9,23.1,...,94958.0,81915.0,9657.0,4.4,10.0,4.0,3.2,1.3,30.4,75.0
2014-15,566484.0,81.3,0.6,13.5,23.0,42.2,19.6,4.7,10.0,16.6,...,95572.0,82444.0,9725.0,4.3,10.0,4.0,2.6,1.0,32.6,75.0
2015-16,565646.0,80.3,0.4,14.7,23.0,42.6,19.6,4.6,10.5,10.1,...,95723.0,82737.0,9754.0,4.2,10.0,4.0,3.0,1.1,33.3,75.0

array(['Total Teachers (Elementary)', '% Teachers: Government',
       '% Teachers: Private Aided', '% Teachers: Private Unaided',
       'Pupil-Teacher Ratio: Elementary', '% Female Teachers',
       '% SC Teachers', '% ST Teachers', '% OBC Teachers',
       '% Teachers Recieved in-Service Training', 'Enrolment: Classes I-V',
       'Enrolment: Classes VI-VIII', 'Enrolment: Classes I-V, Government',
       'Enrolment:Classes VI-VIII,7G8.o5vernment',
       'Enrolment: C1la8s.8ses I-V, Private',
       'Enrolment: Classes VI-VIII, Private',
       '% Girls Enrolment: P5r3im.2ary Level',
       '% Girls Enrol1m9e.1nt: U.Primary Level',
       'Ratio of Girls Enr.to Boys: Primary',
       'Ratio of Girls Enr.to Boys: U.Primary',
       '% SC Enrolment: Classes I-VIII',
       '% ST Enrolment: Cla5s2s.e5s  I-VIII',
       '% OBC Enrolment: Primary Level', '% OBC Enrolment:U.Primary Level',
       '% Muslim Enrolment5: 1P.6rimary Level',
       '% Muslim En1ro9.lm5 ent: U. Primary Level',
       'Ratio of Grade V to I', 'Avg. Repetition Rate: Primary Level',
       'Avg.Repetition Rate: U.Primary Level',
       'Avg. Drop-out Rate: 5P0r.i9mary Level',
       'Retention Rate: Primary Level',
       'Transition Rate: Primary to U.Primary', 'Student-Classroom Ratio',
       '% Schools with Drinking Water', '% Schools with Common Toilet',
       "% Schools with Boys' Toilet", "% Schools with Girls' Toilet",
       '% Schools with Boundarywall', '% School with Playground Facility',
       '% Schools with Ramp', '% Schools havining Electricity',
       '% Schools with Computer', 'Number of Districts 4C.0overed',
       'Total Schools', 'Total Government Schools',
       'Total Private Schools',
       'Ratio of Primary to U.P5r.i0marySch./Sec.',
       'Primary Sch./Sec.per 1000 Child Popln.',
       'U.Prim. Sch./Sec.per 1000 Child Popln.',
       '% Single-Teacher Schools with Enr.\xe2\x89\xa515',
       '% Enrolment in Single-Teacher Schools',
       '% Schools with Enro4l.m3 ent \xe2\x89\xa4 50',
       '% Schools with Fem4a.1le Teachers'], dtype=object)

In [662]:
df.replace(0.0,np.nan)

indicators,Total Teachers (Elementary),% Teachers: Government,% Teachers: Private Aided,% Teachers: Private Unaided,Pupil-Teacher Ratio: Elementary,% Female Teachers,% SC Teachers,% ST Teachers,% OBC Teachers,% Teachers Recieved in-Service Training,...,Total Schools,Total Government Schools,Total Private Schools,Ratio of Primary to U.P5r.i0marySch./Sec.,Primary Sch./Sec.per 1000 Child Popln.,U.Prim. Sch./Sec.per 1000 Child Popln.,% Single-Teacher Schools with Enr.≥15,% Enrolment in Single-Teacher Schools,% Schools with Enro4l.m3 ent ≤ 50,% Schools with Fem4a.1le Teachers
2005-06,234278.0,NaN,NaN,NaN,54.0,27.7,NaN,NaN,NaN,33.1,...,59223.0,NaN,NaN,5.3,6.0,2.0,4.9,2.1,8.8,52.8
2007-08,274052.0,92.9,4.9,2.2,48.0,32.4,19.5,4.5,6.7,51.6,...,70010.0,57461.0,12523.0,5.6,7.0,2.0,3.1,1.2,15.3,68.5
2008-09,272923.0,91.8,5.4,2.8,47.0,33.6,19.6,4.6,7.0,50.6,...,70771.0,57344.0,13427.0,5.5,2.0,8.0,4.0,1.5,18.4,70.4
2009-10,381018.0,82.3,1.4,16.4,39.0,43.1,18.1,4.1,7.1,42.1,...,88556.0,77181.0,11362.0,5.5,10.0,3.0,5.5,2.3,15.8,73.0
2010-11,494297.0,83.9,0.8,11.2,30.0,41.2,18.8,4.4,7.5,28.9,...,90187.0,79119.0,8708.0,5.1,10.0,3.0,2.6,1.0,18.5,74.1
2011-12,529703.0,84.6,0.6,10.7,28.0,41.0,19.3,4.5,7.9,32.7,...,92066.0,81363.0,8273.0,4.7,10.0,3.0,2.7,1.0,19.8,75.0
2012-13,537047.0,82.8,0.7,12.4,27.0,41.6,19.3,4.6,8.4,36.3,...,94572.0,82259.0,9445.0,4.5,10.0,3.0,3.3,1.1,23.0,74.8
2013-14,536830.0,81.6,0.7,13.1,25.0,42.0,19.4,4.8,8.9,23.1,...,94958.0,81915.0,9657.0,4.4,10.0,4.0,3.2,1.3,30.4,75.0
2014-15,566484.0,81.3,0.6,13.5,23.0,42.2,19.6,4.7,10.0,16.6,...,95572.0,82444.0,9725.0,4.3,10.0,4.0,2.6,1.0,32.6,75.0
2015-16,565646.0,80.3,0.4,14.7,23.0,42.6,19.6,4.6,10.5,10.1,...,95723.0,82737.0,9754.0,4.2,10.0,4.0,3.0,1.1,33.3,75.0

In [663]:
sf = SFrame(data=df)

In [664]:
model = gl.linear_regression.create(sf, target="Transition Rate: Primary to U.Primary", features=['Total Teachers (Elementary)', '% Teachers: Government',
       '% Teachers: Private Aided', '% Teachers: Private Unaided',
       'Pupil-Teacher Ratio: Elementary', '% Female Teachers',
       '% SC Teachers', '% ST Teachers', '% OBC Teachers',
       '% Teachers Recieved in-Service Training', 'Enrolment: Classes I-V',
       'Enrolment: Classes VI-VIII', 'Enrolment: Classes I-V, Government',
       'Enrolment:Classes VI-VIII,7G8.o5vernment',
       'Enrolment: C1la8s.8ses I-V, Private',
       'Enrolment: Classes VI-VIII, Private',
       '% Girls Enrolment: P5r3im.2ary Level',
       '% Girls Enrol1m9e.1nt: U.Primary Level',
       'Ratio of Girls Enr.to Boys: Primary',
       'Ratio of Girls Enr.to Boys: U.Primary',
       '% SC Enrolment: Classes I-VIII',
       '% ST Enrolment: Cla5s2s.e5s  I-VIII',
       '% OBC Enrolment: Primary Level', '% OBC Enrolment:U.Primary Level',
       '% Muslim Enrolment5: 1P.6rimary Level',
       '% Muslim En1ro9.lm5 ent: U. Primary Level',
       'Ratio of Grade V to I', 'Avg. Repetition Rate: Primary Level',
       'Avg.Repetition Rate: U.Primary Level',
       'Avg. Drop-out Rate: 5P0r.i9mary Level',
       'Retention Rate: Primary Level',
       'Student-Classroom Ratio',
       '% Schools with Drinking Water', '% Schools with Common Toilet',
       "% Schools with Boys' Toilet", "% Schools with Girls' Toilet",
       '% Schools with Boundarywall', '% School with Playground Facility',
       '% Schools with Ramp', '% Schools havining Electricity',
       '% Schools with Computer', 'Number of Districts 4C.0overed',
       'Total Schools', 'Total Government Schools',
       'Total Private Schools',
       'Ratio of Primary to U.P5r.i0marySch./Sec.',
       'Primary Sch./Sec.per 1000 Child Popln.',
       'U.Prim. Sch./Sec.per 1000 Child Popln.',
       '% Single-Teacher Schools with Enr.\xe2\x89\xa515',
       '% Enrolment in Single-Teacher Schools',
       '% Schools with Enro4l.m3 ent \xe2\x89\xa4 50',
       '% Schools with Fem4a.1le Teachers'])

WARNING: The number of feature dimensions in this problem is very large in comparison with the number of examples. Unless an appropriate regularization value is set, this model may not provide accurate predictions for a validation/test set.

Linear regression:

--------------------------------------------------------

Number of examples          : 10

Number of features          : 52

Number of unpacked features : 52

Number of coefficients    : 53

Starting Newton Method

--------------------------------------------------------

+-----------+----------+--------------+--------------------+---------------+

| Iteration | Passes   | Elapsed Time | Training-max_error | Training-rmse |

+-----------+----------+--------------+--------------------+---------------+

| 1         | 2        | 0.000902     | 0.166830           | 0.084285      |

+-----------+----------+--------------+--------------------+---------------+

SUCCESS: Optimal solution found.

In [665]:
print model.coefficients

+-------------------------------+-------+-------------------+--------+
|              name             | index |       value       | stderr |
+-------------------------------+-------+-------------------+--------+
|          (intercept)          |  None |   21.9910539756   |  None  |
|  Total Teachers (Elementary)  |  None | 2.19238427896e-06 |  None  |
|     % Teachers: Government    |  None |  0.0558626377406  |  None  |
|   % Teachers: Private Aided   |  None |   1.51576106072   |  None  |
|  % Teachers: Private Unaided  |  None |   0.428317980153  |  None  |
| Pupil-Teacher Ratio: Eleme... |  None |  -0.0510514816604 |  None  |
|       % Female Teachers       |  None |  0.0350798007535  |  None  |
|         % SC Teachers         |  None |   0.22915563667   |  None  |
|         % ST Teachers         |  None |   1.00452436299   |  None  |
|         % OBC Teachers        |  None |   0.506422431028  |  None  |
+-------------------------------+-------+-------------------+--------+
[53 rows x 4 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [666]:
print type(model.coefficients)

<class 'graphlab.data_structures.sframe.SFrame'>

In [667]:
result = model.coefficients.to_dataframe()

In [668]:
display(result)

                                         name index         value stderr
0                                 (intercept)  None  2.199105e+01   None
1                 Total Teachers (Elementary)  None  2.192384e-06   None
2                      % Teachers: Government  None  5.586264e-02   None
3                   % Teachers: Private Aided  None  1.515761e+00   None
4                 % Teachers: Private Unaided  None  4.283180e-01   None
5             Pupil-Teacher Ratio: Elementary  None -5.105148e-02   None
6                           % Female Teachers  None  3.507980e-02   None
7                               % SC Teachers  None  2.291556e-01   None
8                               % ST Teachers  None  1.004524e+00   None
9                              % OBC Teachers  None  5.064224e-01   None
10    % Teachers Recieved in-Service Training  None -7.120738e-02   None
11                     Enrolment: Classes I-V  None -4.261153e-08   None
12                 Enrolment: Classes VI-VIII  None  2.009890e-07   None
13         Enrolment: Classes I-V, Government  None  5.274940e-07   None
14   Enrolment:Classes VI-VIII,7G8.o5vernment  None  1.166246e-06   None
15        Enrolment: C1la8s.8ses I-V, Private  None  4.442185e-06   None
16        Enrolment: Classes VI-VIII, Private  None  1.359749e-05   None
17       % Girls Enrolment: P5r3im.2ary Level  None -2.270954e-03   None
18     % Girls Enrol1m9e.1nt: U.Primary Level  None  1.303382e-03   None
19        Ratio of Girls Enr.to Boys: Primary  None -2.384275e-01   None
20      Ratio of Girls Enr.to Boys: U.Primary  None  6.148260e-02   None
21             % SC Enrolment: Classes I-VIII  None -1.433025e-03   None
22        % ST Enrolment: Cla5s2s.e5s  I-VIII  None  5.129932e-02   None
23             % OBC Enrolment: Primary Level  None  2.340636e-01   None
24            % OBC Enrolment:U.Primary Level  None  1.492680e-01   None
25      % Muslim Enrolment5: 1P.6rimary Level  None  1.521310e-01   None
26  % Muslim En1ro9.lm5 ent: U. Primary Level  None  1.535348e-01   None
27                      Ratio of Grade V to I  None -2.038280e-02   None
28        Avg. Repetition Rate: Primary Level  None -6.300862e-01   None
29       Avg.Repetition Rate: U.Primary Level  None  4.424615e-01   None
30      Avg. Drop-out Rate: 5P0r.i9mary Level  None -3.289201e-01   None
31              Retention Rate: Primary Level  None  6.161617e-03   None
32                    Student-Classroom Ratio  None -4.792129e-02   None
33              % Schools with Drinking Water  None  7.484443e-04   None
34               % Schools with Common Toilet  None  7.257508e-03   None
35                % Schools with Boys' Toilet  None  4.303700e-02   None
36               % Schools with Girls' Toilet  None -2.020698e-02   None
37                % Schools with Boundarywall  None -5.232332e-02   None
38          % School with Playground Facility  None  1.772058e-01   None
39                        % Schools with Ramp  None  2.629750e-02   None
40             % Schools havining Electricity  None -5.094382e-02   None
41                    % Schools with Computer  None  2.141494e-01   None
42             Number of Districts 4C.0overed  None  1.656400e-02   None
43                              Total Schools  None  1.277303e-05   None
44                   Total Government Schools  None  5.569382e-05   None
45                      Total Private Schools  None  4.980592e-04   None
46  Ratio of Primary to U.P5r.i0marySch./Sec.  None  1.845459e-01   None
47     Primary Sch./Sec.per 1000 Child Popln.  None  4.968368e-01   None
48     U.Prim. Sch./Sec.per 1000 Child Popln.  None -1.066656e+00   None
49      % Single-Teacher Schools with Enr.≥15  None -1.130966e+00   None
50      % Enrolment in Single-Teacher Schools  None -1.469328e+00   None
51          % Schools with Enro4l.m3 ent ≤ 50  None  1.411295e-01   None
52          % Schools with Fem4a.1le Teachers  None  1.344066e-02   None

In [669]:
result.to_csv(india_folder +"reg_coefficient/west_bengal_result.csv", index=False)